# Generated by Django 5.2.4 on 2025-08-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_create_book', 'Can create new book'), ('can_edit_book', 'Can edit books'), ('can_delete_book', 'Can delete books'), ('can_view_book', 'Can view book')]},
        ),
    ]
