# Generated by Django 5.2.4 on 2025-07-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0002_alter_book_options_alter_library_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'Can add a new book'), ('can_change_book', 'Can change existing books'), ('can_delete_book', 'Can delete books')]},
        ),
    ]
